services:
  auth_service:
    build:
      context: authorization
      dockerfile: Dockerfile
    container_name: auth_service
    networks:
      - internal_network
    expose:
      - "8081"

  websocket_chat:
    build:
      context: chat
      dockerfile: Dockerfile
    container_name: websocket_chat
    ports:
      - "8080:8080"
    depends_on:
      - auth_service
      - mysql
    networks:
      - internal_network

  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306"
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
